---
extends:
  - peakfijn
  - prettier
  - prettier/react
parser: babel-eslint
plugins:
  - filenames
  - jest
env:
  browser: true
  jest/globals: 'on'
settings:
  import/resolver:
    node:
      moduleDirectory:
        - node_modules
        - src/
rules:
  max-len: [error, 120]

  no-tabs: off
  indent:
    - error
    - tab
    - SwitchCase: 1

  react/jsx-filename-extension: off
  react/jsx-indent: [error, tab]
  react/jsx-indent-props: [error, tab]
  import/extensions:
    - off
    - never
  filenames/match-regex:
    - error
    - ^[a-z_-]+(\.(android|ios))?(\.test)?$
    - true
  react/jsx-wrap-multilines:
    - off
  jsx-a11y/click-events-have-key-events:
    - off
  jsx-quotes: [error, "prefer-double"]
